CREATE TABLE USERS(
ID INT NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
ROL VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE CURRENCY(
ID INT NOT NULL AUTO_INCREMENT,
COINT VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE AUDIT_EXCHANGE(
ID INT NOT NULL AUTO_INCREMENT,
COINT_ONE INT NOT NULL,
COINT_TWO INT NOT NULL,
BUY NUMERIC(10, 3) NOT NULL,
SALE NUMERIC(10, 3) NOT NULL,
DATE_AUDIT DATETIME NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TYPE_EXCHANGE(
COINT_ONE INT NOT NULL,
COINT_TWO INT NOT NULL,
BUY NUMERIC(10, 3) NOT NULL,
SALE NUMERIC(10, 3) NOT NULL,
FOREIGN KEY (COINT_ONE) REFERENCES CURRENCY(ID),
FOREIGN KEY (COINT_TWO) REFERENCES CURRENCY(ID)
);




INSERT INTO USERS
VALUES(1,'Dan','dan@gmail.com','$2a$12$mPWAGud3YvP9jNL.B6YjBu2hrJLaqXxLrr.wI9/jp5x/BUMJYdC.a','ADMIN'),
(2,'David','david@gmail.com','$2a$12$mPWAGud3YvP9jNL.B6YjBu2hrJLaqXxLrr.wI9/jp5x/BUMJYdC.a','USERS');


INSERT INTO CURRENCY
VALUES(1,'Sol Peruano'),
(2,'Dolar EstadoUnidense'),
(3,'Peso Chileno'),
(4,'Peso Argentino');


INSERT INTO TYPE_EXCHANGE
VALUES
(1, 2, 3.755, 3.780),
(1, 3, 4.608, 4.668);
